esphome:
  name: esp1
  friendly_name: ESP1

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "fXZQ5/dctmlqcy2W0bA37kcRDqOnaii/xeLjln3PerI="

ota:
  - platform: esphome
    password: "a4523890996d4675040d23b4787486ea"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp1 Fallback Hotspot"
    password: "EWpE8iQ2p2EH"

captive_portal:

sensor:
  - platform: dht
    pin: GPIO2
    model: DHT22
    temperature:
      name: "Kinderzimmer Temperatur"
      id: kinderzimmer_temp
      filters:
        - offset: -7.0
    humidity:
      name: "Kinderzimmer Luftfeuchtigkeit"
      id: kinderzimmer_luf
    update_interval: 60s
