esphome:
  name: "esptempkind"
  friendly_name: espTempKind

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "7kI6zT28uZJQG06SWyKTlACjX0+EXsxCcnRBPBD61nY="

ota:
  - platform: esphome
    password: "657e754394088eb71bf71f653707e9a3"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "EspKind Fallback Hotspot"
    password: "O5sVVadDKkDG"

captive_portal:

sensor:
  - platform: dht
    pin: GPIO2
    #model: DHT22
    temperature:
      name: "Kinderzimmer Temperatur"
      id: kinderzimmer_temp
      filters:
        - offset: -7.7
    humidity:
      name: "Kinderzimmer Luftfeuchtigkeit"
      id: kinderzimmer_luf
    update_interval: 150s

switch:
  - platform: gpio
    pin:
      number: GPIO01
      inverted: true
    id: gpio01
    name: 'gpio01'
  - platform: restart
    name: resEspTempKind
    id: resEspTempKind
